"""Prose for the map's guide and the report's fixed sections. Numbers are filled in by assemble.py."""

GUIDE_INTRO = [
    "The Wider Field maps organisations that bring knowledge from outside mainstream AI safety to the question of how advanced AI can go well. It was made for the integral altruism (int/a) community, after a conversation in the int/a Europe group in October 2026 about widening the field, not only founding more organisations of the kind it already has.",
    "The classic map of the field, at aisafety.com, sorts about 370 entries by what they do: research, governance, advocacy, funding. It says little about adjacent fields. This map starts from the other end: which body of knowledge, practice or tradition each organisation brings, what it works on, and how close it sits to the AI-safety core.",
    "It is meant for funders looking for what their grantees aren't using, founders looking for empty niches, people in other fields looking for where they fit, AI-safety insiders looking for blind spots, and int/a members looking for their own milieu.",
]

GUIDE_READ = [
    "Each of the 14 sectors is a tradition: a body of knowledge or practice, such as the life sciences, contemplative traditions or democratic theory. An organisation sits in its home tradition, the one its AI work draws on most; the traditions it also draws on are listed in its entry. Neighbouring sectors are intellectually close, so bridges tend to form across a border.",
    "The four rings measure distance from the AI-safety core, not quality or importance. Core organisations exist to make advanced AI go well. Bridge organisations are rooted elsewhere but work explicitly on AI safety or on AI going well. Adjacent organisations work on AI's human and social effects without a catastrophic-risk framing. Potential partners hold relevant knowledge or methods but have done little on AI so far.",
    "Hatched cells are places the search found nothing. Some are real openings; others reflect the limits of a mostly English-language web search. Click one to read which. Outlined marks are organisations already on the aisafety.com map. The eight generalist funders, who fund across many traditions, sit in a dashed band just outside the wheel; hover over one to see which traditions it reaches.",
    "Colour and shape show one more dimension at a time: the problem area an organisation mainly works on (the default), the integral quadrant its work attends to, what flows where (does its knowledge reach the AI models, the people who build them, institutions, or mainly its own community?), or what it says is at stake. Shapes repeat the colours, so the map reads without colour vision.",
]

BRIEF_HTML = """
<p>In October 2026, members of the int/a Europe group discussed a project worth doing: mapping the fields adjacent to AI safety, for existing and possible AI-safety work, and making them legible to existing and new funders. The prompt was a contrast. There is much talk about founding more AI-safety organisations (Coefficient Giving's Project Tailwind, a $200 million call for founders, is the latest), and little about widening the field. New funders are arriving and looking for approaches that haven't been tried.</p>
<p>A second point came from a conversation with the aisafety.com team, who were updating their field map. Adjacent fields weren't its focus, which is reasonable for the core, but it leaves blind spots: the field doesn't see where other disciplines already have approaches or knowledge, and risks becoming more myopic over time. The group asked for a concrete list of problems for founders and opportunities for funders, and suggested the int/a project might be the mapping itself, done as an interdisciplinary exercise. Princint (formerly PIBBSS), the Alignment of Complex Systems group and the cooperative-AI community were named as places where this kind of work already happens.</p>
<p>The brief points in a direction rather than fixing a scope, so four decisions shaped this report.</p>
<ul>
<li><b>The unit is the organisation.</b> Labs, nonprofits, programmes, funders, networks, professional bodies and companies, not essays or individuals. The essays and talks in the seed list appear as the key work of the organisations behind them.</li>
<li><b>"AI going well" is read broadly.</b> Many adjacent fields don't use the language of existential risk, and excluding them would reproduce the blind spot. The rings keep the difference visible: an organisation's distance from the AI-safety core is shown, not hidden.</li>
<li><b>The main axis is the adjacent field.</b> Each organisation is placed by the tradition of knowledge it brings, which is what the brief asked to make legible. What it works on is a second, independent axis, so the two can be crossed to find empty niches.</li>
<li><b>Possible work counts too.</b> The brief mentions possible as well as existing AI-safety work, so the map includes potential partners: organisations whose knowledge is plainly relevant but which have barely engaged with AI. These are the doors a founder or funder would have to open.</li>
</ul>
"""

ORGANISED_HTML = """
<p>Every organisation is tagged on a handful of facets, each answering one question a reader might ask. The categories were designed by four independent designers working from different starting points (by discipline, by problem, through int/a's integral frames, and by what each kind of reader needs to find), scored by two judges with opposite priorities (a sceptical funder and map editor; an int/a steward and interdisciplinary facilitator), and merged by a synthesiser. The definitions are in the map's Guide tab.</p>
<p><b>Tradition: what it brings.</b> Fourteen traditions, grouped into four families. <i>Sciences &amp; engineering</i>: safety and risk sciences; formal and physical sciences; life and systems sciences. <i>Minds &amp; inner life</i>: consciousness and AI minds; psychology and cognitive science; contemplative and integral traditions; religion and theology. <i>Humanities &amp; cultures</i>: philosophy and ethics; arts, narrative and futures; Indigenous and decolonial knowledges. <i>Society &amp; institutions</i>: law, rights and society; economics, labour and commons; democracy and collective intelligence; peace, security and diplomacy. Each organisation has one home tradition and up to two others it draws on substantially.</p>
<p><b>Ring: how close it is to the AI-safety core.</b> Core, bridge, adjacent and potential, as defined above. A ring is a statement about proximity, not worth: much of the most interesting work on this map sits in the outer rings.</p>
<p><b>Problem: what it works on.</b> Fourteen problems in four areas. <i>The AI itself</i>: understanding AI and agency; what AI should value; assurance and oversight; the moral status of AI. <i>Human minds &amp; meaning</i>: protecting minds and relationships; meaning, dignity and formation; the people doing the work. <i>Living &amp; deciding together</i>: sensemaking, truth and foresight; democratic voice and legitimacy; rights and plural voices; power, wealth and work. <i>Cooperation, conflict &amp; civilisation</i>: multi-agent AI and cooperation; security and international coordination; systemic risk and the metacrisis.</p>
<p><b>Lenses.</b> A few further facets are there to see the field differently. <i>What flows where</i> asks who or what changes because of the work: the AI models, the people who build and govern them, institutions, or mainly the organisation's own community. The <i>integral quadrant</i> asks whether the work attends to inner experience (I), shared meaning (We), mechanisms (It) or collective systems (Its). <i>What is at stake</i> records how the organisation itself frames the stakes. <i>Way of knowing</i> records what kind of knowledge its main output is, from formal proof to contemplative practice to communal and lived knowledge. Sparse <i>int/a badges</i> mark clear exemplars of one of int/a's five principles. Practical facets cover what the organisation does, how to get involved, type, region, status and nearness to int/a's hubs.</p>
"""
